spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/tutorial
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: /rkJ2GYI/6nJUw3F8nbgGNgx9oPAU+kHM0Y1VoMCTVE=
  expiration: 86400000
